config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions'}
  root 'books#index'
  resources :books
  get '/books/:id/return', to: 'books#book_return', as: "return_book"
  get '/books/:id/request_book', to: 'books#request_book', as:"request_book"
  post 'books/:id/', to: 'books#reserve'
  resources :users

end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :library
    has_many :histories
    has_many :bookrequests
    has_many :check_outs
    has_many :users, through: :check_outs
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :return]
  

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    
    

  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reserve
    @bookCopy= Book.find(params[:id])
    @bookCopy.histories.create(email: current_user.email, chkDate: Date.today, copy: @bookCopy.copies)
    
    current_user.check_outs.create(book_id: @bookCopy.id,
                                   checkout_date: Date.today,
                                   bookTitle: @bookCopy.title,
                                   returnDate: (Date.today + 7),
                                   email: current_user.email, 
                                   copy: @bookCopy.copies,
                                   libName: @bookCopy.libName)
    @bookCopy.copies -= 1 
    @bookCopy.save
   
    
   
    redirect_to @bookCopy, notice: @bookCopy.title + ' was successfully checked out.' 
    
    
  end

  def book_return
    @bookCopy = Book.find(params[:id])
    @bookCopy.copies += 1 
    @bookCopy.save
    
    if(@bookCopy.bookrequests.length > 0)
       AppmailerMailer.send_notice(@bookCopy).deliver_now
       @bookCopy.bookrequests.destroy_all
    end
    

   current_user.books.destroy(Book.find_by_id(@bookCopy))

   @history = @bookCopy.histories.where(email: current_user.email).last 

   @history.returnedOn = Date.today
   @history.save
   redirect_to current_user, notice: 'Book was successfully returned.'
  end
  
  def request_book 
    @bookCopy = Book.find(params[:id])
    @bookCopy.bookrequests.create(email: current_user.email,libName: @bookCopy.libName)
    redirect_to @bookCopy, notice: @bookCopy.title + ' was successfully requested.'
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:libName,:title, :author, :genre, :subgenre, :pages, :publisher, :copies)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :subgenre %><br>
    <%= f.text_field :subgenre %>
  </div>
  <div class="field">
    <%= f.label :pages %><br>
    <%= f.number_field :pages %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :copies %><br>
    <%= f.number_field :copies %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Library App P2', root_path , class: "navbar-brand"%>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
         <%if user_signed_in?%>
            <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path,method: :delete, class:"nav-link"%>
            </li>
            <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
          <%= link_to 'View books taken', current_user ,class:"nav-link"%>
          </li>
         <% else %>
            <li class="nav-item">
            <%= link_to 'Sign in',new_user_session_path , class:"nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class:"nav-link"%>
            </li>
         <% end %>
          <%if current_user && current_user.admin%>
          <li class="nav-item">
          <%= link_to 'Add New Book', new_book_path ,class:"nav-link"%>
          </li>
          <% end %>
      </ul>
      
    </div>
  </div>
</nav>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>                 

<table class="table table-light table-hover">
  <thead>
    <tr>
      <th>Available At</th> 
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Subgenre</th>
      <th>Publisher</th>
      <th>Copies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.order([:title]).each do |book| %>
      <tr>
        <td><%= book.libName %></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td><%= book.subgenre %></td>
        
        <td><%= book.publisher %></td>
        <td><%= book.copies %></td>
        <td><%= link_to 'Details', book,class:"btn btn-secondary" %></td>
        <%if current_user && current_user.admin%>
        <td><%= link_to 'Edit Book', edit_book_path(book) %></td>
        <td><%= link_to 'Remove from library', book, method: :delete, data: { confirm: 'Are you sure you want to delete this book?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <h1 class="display-4"><%= @book.title %></h1>
  <p class="lead">
   <br>
   Author: <%= @book.author %> <br><br>
   Genre: <%= @book.genre %><br><br>
   Subgenre: <%= @book.subgenre %><br><br>
   Pages: <%= @book.pages %><br><br>
   Publisher: <%= @book.publisher %><br><br>
   Copies: <%= @book.copies %><br><br>
   Available At: <%= @book.libName %><br><br>
   <% if user_signed_in? && current_user.admin %>
  
        Current Users with this book<br>
     
    
         <% @book.check_outs.each do |user| %>
           <%= user.email%> &nbsp;&nbsp; copy: <%= user.copy%><br>

        <% end %>
    
        Book History<br>
    
        <% @book.histories.each do |history| %>
        <%= history.email%> &nbsp;&nbsp; copy: <%= history.copy%> &nbsp;&nbsp; Checkout Date: <%= history.created_at.to_date%>
        &nbsp;&nbsp; Return Date: <%= history.returnedOn%><br>
      <%end%> 
  
      
    

      
    
   <% end %>
  </p>
  <hr class="my-4">
  <%if current_user && @book.copies == 0%>
   <%= link_to "Request Book",request_book_path, class: "btn btn-secondary"%>
  <% end %>
  <%if current_user && @book.copies > 0%>
    <%if current_user.check_outs.length == 0%>
      <%= link_to "Reserve Book",@book_reserve,method: :post, class: "btn btn-secondary"%>
    <%else%>
      <%current_user.check_outs.each do |user_book|%>
        <% if user_book.bookTitle != @book.title %>
         <%= link_to "Reserve Book",@book_reserve,method: :post, class: "btn btn-secondary"%>
       <% end %>
     <% end %>
   <% end %>  
  <% end %>
  
  <%if current_user && current_user.admin%>
    <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-secondary'%> 
    <% end %>
 <%= link_to 'Back', books_path,
  class: 'btn btn-dark'%>
</div>